/* eslint-disable test/no-import-node-test */
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

test('supports native whole-group move with anchor fallback', async () => {
	const bundle = await readFile(new URL('../dist/iframe.js', import.meta.url), 'utf8');
	const source = await readFile(new URL('../iframe/app.mjs', import.meta.url), 'utf8');
	const html = await readFile(new URL('../iframe/index.html', import.meta.url), 'utf8');
	const css = await readFile(new URL('../iframe/styles.css', import.meta.url), 'utf8');
	const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
	const packageMetadata = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
	const edaignore = await readFile(new URL('../.edaignore', import.meta.url), 'utf8');
	const workflow = await readFile(new URL('../.github/workflows/ci.yml', import.meta.url), 'utf8');
	const placement = bundle.indexOf('placeComponentWithMouse');
	const followTip = bundle.indexOf('showFollowMouseTip', placement);
	const hideWindow = bundle.indexOf('hideIFrame', placement);

	assert.ok(placement >= 0);
	assert.ok(followTip > placement);
	assert.ok(hideWindow > placement);
	assert.match(bundle, /doCommand\(['"]draw_end['"]\)/);
	assert.match(source, /doCommand\('MOVE_BY_CENTER_POINT'\)/);
	assert.match(source, /doCommand\('align_grid'\)/);
	const wholeGroupPlacement = source.indexOf('async function placeDomainsAsMovedGroups');
	const alignToGrid = source.indexOf('doCommand(\'align_grid\')', wholeGroupPlacement);
	const placementValidation = source.indexOf('await validateStagedDomainPlacement(staged, domain)', alignToGrid);
	assert.ok(wholeGroupPlacement >= 0);
	assert.ok(alignToGrid > wholeGroupPlacement);
	assert.ok(placementValidation > alignToGrid);
	assert.match(source, /areCoordinatesOnGrid/);
	assert.match(source, /createCanvasPlacementWaiter/);
	assert.match(source, /PLACEMENT_CANCELLED/);
	assert.match(source, /Esc 取消/);
	assert.match(source, /当前未完成的组已清理/);
	assert.doesNotMatch(source, /await sleep\(250\)/);
	assert.match(source, /Promise\.all\(staged\.capacitorIds\.map/);
	assert.match(source, /createStagedDomainGroup/);
	assert.ok(source.indexOf('clearSelected()') < source.indexOf('doSelectPrimitives(ids)'));
	assert.match(source, /nextCapacitorDesignators/);
	assert.match(source, /validateStagedDomainPlacement/);
	assert.match(source, /已整块放置并校验/);
	assert.doesNotMatch(source, /restoreStagedNetLabels|setState_Net\(/);
	assert.doesNotMatch(source, /\\u2063/);
	assert.doesNotMatch(source, /doCommand\('cut'\)|doCommand\('paste'\)/);
	assert.match(bundle, /getSelectedLibraryRowInfo/);
	assert.match(bundle, /openBottomPanel/);
	assert.match(bundle, /ESYS_BottomPanelTab/);
	assert.match(bundle, /watchNativeDeviceSelection/);
	assert.doesNotMatch(bundle, /useCurrentNativeDevice/);
	assert.match(bundle, /hideIFrame/);
	assert.match(bundle, /capacitorDevices\.v2/);
	assert.match(bundle, /capacitorValues\.v1/);
	assert.match(bundle, /preferences\.v1/);
	assert.match(source, /restorePersistentPreferences/);
	assert.match(source, /if \(!preferences\)\s+await savePreferences\(\)/);
	assert.match(bundle, /selectClosestPlacedComponent/);
	assert.match(bundle, /removeExtraPlacementAnchors/);
	assert.match(bundle, /extractDeviceCapacitance/);
	assert.match(bundle, /mapConcurrent/);
	assert.match(bundle, /placeDomainsSequentiallyWithMouse/);
	assert.match(bundle, /totalCaps/);
	assert.match(bundle, /buildSharedBusPlan/);
	assert.match(bundle, /sch_PrimitiveAttribute\.getAll/);
	assert.match(bundle, /gridSize\s*=\s*10/);
	assert.match(bundle, /targetX\s*=\s*x\s*\+\s*gridSize/);
	assert.doesNotMatch(bundle, /targetX\s*=\s*x\s*-\s*gridSize/);
	assert.match(html, /class="action-dock"/);
	assert.match(html, /data-global-cap-value="bulk"/);
	assert.match(html, /data-global-cap-value="pin"/);
	assert.match(html, /class="pins-drawer"/);
	assert.doesNotMatch(html, /historyPanel|生成记录/);
	assert.match(source, /class="domain-summary"/);
	assert.match(html, /<span>网络名称<\/span><span>引脚号<\/span>/);
	assert.match(source, /pins\.map\(pin => `Pin \$\{pin\.number\}`\)/);
	assert.match(source, /<span>Pin \$\{escapeHtml\(pin\.number\)\}<\/span>/);
	assert.match(source, /class="summary-bulk-toggle"/);
	assert.match(html, /class="notice-stack"/);
	assert.match(css, /grid-template-rows:\s*36px auto minmax\(0, 1fr\) 54px/);
	assert.match(css, /grid-auto-rows:\s*max-content/);
	assert.match(css, /height:\s*100vh/);
	assert.doesNotMatch(html, /data-use-current-device|Bulk|Bypass/);
	assert.doesNotMatch(html, /STEP 1|STEP 2|STEP 3|placement-preview/);
	assert.doesNotMatch(source, /createPowerFlag\(domain\.label, pin\.x, pin\.y\)/);
	assert.doesNotMatch(source, /MANIFESTS_STORAGE_KEY|state\.manifests|替换现有去耦/);
	assert.match(source, /本次 \$\{totalCaps\} 颗/);
	assert.match(source, /整块放置 \$\{summary\.domains\} 个电源域/);
	assert.match(source, /第 \$\{index \+ 1\}\/\$\{domains\.length\} 组/);
	assert.match(source, /await sleep\(20\)/);
	assert.match(readme, new RegExp(`!\\[原理图自动去耦喵操作演示\\]\\(https://cdn\\.jsdelivr\\.net/gh/MeowKJ/lceda-decoupling-meow@v${packageMetadata.version.replaceAll('.', '\\.')}\\/images\\/usage-demo\\.gif\\)`));
	assert.doesNotMatch(readme, /data:image|;base64,/i);
	assert.match(edaignore, /^\/images\/usage-demo\.gif$/m);
	assert.match(workflow, /gh release create[^\n]*images\/usage-demo\.gif/);
});
